### ISSUE TITLE
[Bug]: Non-ghost tapping input just plain is working stupidly

### ISSUE THREAD

**Issue by SpunBlue** [thepercentageguy/NUFNF#1]
### Contact Details

SpunBlue#8248

### What happened?

- Hitting a note and hitting another key that doesn't have a note will not count as a Miss
- Hitting 2 keys with no notes will only count as 1 miss
- Unrelated: Text should be above the Player Icons as the text is pretty hard to see with the icons over the text

You can see the issues in this recording of me messing around in the Tutorial Charter:
https://www.youtube.com/watch?v=s5kbBrBCYGk&ab_channel=SpunBlue

Other stuff:
It's still way to easy to get a SICK (Should be harder or customizable maybe?)
SHITS should still subtract the players health to stop spammers.
Note Miss Animations shouldn't play on Ghost Tapping.
Also sometimes you just miss for no reason lol

### Steps to reproduce

"- Hitting a note and hitting another key that doesn't have a note will not count as a Miss
- Hitting 2 keys with no notes will only count as 1 miss"

### Version

2.1.0

**Comment by thepercentageguy** [comment]
> Note Miss Animations shouldn't play on Ghost Tapping.

Input bugs happen if i remove that, plus it's funny.

**Comment by thepercentageguy** [comment]
> Also sometimes you just miss for no reason lol

not specific enough

also please split this up into multiple issues, makes it a lot easier for me

**Comment by SpunBlue** [comment]
> > Also sometimes you just miss for no reason lol
> 
> not specific enough
> 
> also please split this up into multiple issues, makes it a lot easier for me

will do

**Comment by thepercentageguy** [comment]
Please resend this but with only 1 problem.
