### ISSUE TITLE
[Enhancement]: Cutscenes

### ISSUE THREAD

**Issue by SpunBlue** [thepercentageguy/NUFNF#5]
### Contact Details

SpunBlue#8248

### What do you want to see?

Add Cutscenes (With documentation on how to use) so that way i can make my mod have cutscenes lol

**Comment by thepercentageguy** [comment]
MP4 cutscenes are planned

**Comment by SpunBlue** [comment]
cool

**Comment by SpunBlue** [comment]
sorry it was a misclick

**Comment by thepercentageguy** [comment]
added
